#!/usr/bin/env bash
# Stop hook (sync): emits a systemMessage banner ~2 minutes before the
# 1h cache cliff, once HANDOFF.md has been generated by cache-cliff-handoff.sh.
set -uo pipefail

input=$(cat)
transcript=$(printf '%s' "$input" | /usr/bin/jq -r '.transcript_path // empty' 2>/dev/null)
session_id=$(printf '%s' "$input" | /usr/bin/jq -r '.session_id    // "default"' 2>/dev/null)
cwd=$(       printf '%s' "$input" | /usr/bin/jq -r '.cwd           // empty'     2>/dev/null)

session_id=$(printf '%s' "$session_id" | tr -cd 'A-Za-z0-9._-' | head -c 64)
[[ -z "$session_id" ]] && session_id="default"

# Stop fired — clear the busy flag so the next UserPromptSubmit re-sets it.
rm -f "/tmp/claude-cliff-busy-${session_id}"

[[ -z "$transcript" || ! -f "$transcript" ]] && exit 0

now_epoch=$(date +%s)

oldest_ts=$(
  /usr/bin/jq -rs --argjson now "$now_epoch" '
    [ .[]
      | select(.type=="assistant" and (.message.usage // empty))
      | { ts: (try (.timestamp | sub("\\.[0-9]+"; "") | fromdateiso8601) catch 0),
          m1h: (.message.usage.cache_creation.ephemeral_1h_input_tokens // 0) }
    ]
    | [ .[] | select(.ts >= ($now - 3600) and .m1h > 0) ]
    | sort_by(.ts) | first // {ts: 0}
    | .ts | floor
  ' "$transcript" 2>/dev/null
)

oldest_ts=${oldest_ts:-0}

# Test override: echo a future epoch into this file to skip transcript parsing
# e.g. echo $(( $(date +%s) + 300 )) > /tmp/claude-cliff-test-cliff
test_flag="/tmp/claude-cliff-test-cliff"
if [[ -f "$test_flag" ]]; then
  cliff_time=$(cat "$test_flag")
else
  [ "$oldest_ts" -le 0 ] && exit 0
  cliff_time=$(( oldest_ts + 3600 ))
fi

rem=$(( cliff_time - now_epoch ))

# Missed-cliff banner: handoff.sh bailed because the agent was busy. Surface
# this on the next Stop so the user knows the cache was burned and can run
# /handoff to recover. Only emit once (sentinel removed after read).
skipped_sentinel="/tmp/claude-cliff-skipped-busy-${session_id}"
if [ -f "$skipped_sentinel" ]; then
  missed_cliff=0; missed_tokens=0
  read -r missed_cliff missed_tokens < "$skipped_sentinel" || true
  : "${missed_cliff:=0}" "${missed_tokens:=0}"
  rm -f "$skipped_sentinel"
  age=$(( now_epoch - missed_cliff ))
  # Only report a recent miss (within 10 minutes), and only if the cliff
  # has actually passed — handoff.sh might have written the sentinel and
  # then a quick Stop fired before the cliff arrived (rare but possible).
  if [ "$missed_cliff" -gt 0 ] && [ "$age" -ge 0 ] && [ "$age" -le 600 ]; then
    missed_hhmm=$(date -r "$missed_cliff" '+%H:%M' 2>/dev/null \
      || date -d "@$missed_cliff" '+%H:%M' 2>/dev/null \
      || echo "?")
    missed_tokens_fmt=$(printf "%'d" "$missed_tokens" 2>/dev/null || echo "$missed_tokens")
    now_hhmm_local=$(date '+%H:%M')
    msg2="${now_hhmm_local}: Missed 1h cache cliff at ${missed_hhmm} — agent was busy, handoff was skipped to avoid mid-turn interruption."
    msg2+=$'\n'"${missed_tokens_fmt} tokens of cache will need to be re-hydrated on the next prompt."
    msg2+=$'\nRun /handoff now to write the session handoff manually before continuing.'
    /usr/bin/jq -n --arg m "$msg2" '{"systemMessage": $m}'
    exit 0
  fi
fi

ready_sentinel="/tmp/claude-cliff-handoff-ready-${session_id}"
# If the cliff has already passed, cleanup the orphaned ready-sentinel so a
# stale token count from a prior cycle never feeds a future banner.
if [ "$rem" -le 0 ] && [ -f "$ready_sentinel" ]; then
  rm -f "$ready_sentinel" "/tmp/claude-cliff-stats-${session_id}" "/tmp/claude-cliff-perm-requested-${session_id}"
fi
if [ "$rem" -gt 0 ] && [ "$rem" -le 120 ] && [ -f "$ready_sentinel" ]; then
  tokens=$(cat "$ready_sentinel" 2>/dev/null || echo "0")
  tokens_fmt=$(printf "%'d" "$tokens" 2>/dev/null || echo "$tokens")
  session_short="${session_id:0:8}"
  handoff_path="${cwd:-.}/HANDOFF-${session_short}.md"
  now_hhmm=$(date '+%H:%M')
  cliff_hhmm=$(date -r "$cliff_time" '+%H:%M' 2>/dev/null \
    || date -d "@$cliff_time" '+%H:%M' 2>/dev/null \
    || echo "unknown")

  # Check permission status if creation was attempted this cycle
  perm_line=""
  perm_request_sentinel="/tmp/claude-cliff-perm-requested-${session_id}"
  if [ -f "$perm_request_sentinel" ]; then
    added=(); failed=()
    while IFS= read -r pattern; do
      exact_session_form="${pattern/\*/$session_short}"
      found=false
      perm_scope=""
      for sf in "$HOME/.claude/settings.json" "${cwd:-.}/.claude/settings.json"; do
        [[ -f "$sf" ]] || continue
        if /usr/bin/jq -e \
             --arg wild "$pattern" \
             --arg exact "$exact_session_form" \
             '(.permissions.allow // [])[] | select(
                . == "Write(" + $wild + ")"
                or . == "Write(" + $exact + ")"
                or (startswith("Write(") and (endswith("/" + $wild + ")") or endswith("/" + $exact + ")")))
             )' "$sf" &>/dev/null; then
          found=true
          [[ "$sf" == "$HOME/.claude/settings.json" ]] && perm_scope="global" || perm_scope="project"
          break
        fi
      done
      if $found; then added+=("Write($pattern) → $perm_scope")
      else         failed+=("Write($pattern)")
      fi
    done < "$perm_request_sentinel"
    rm -f "$perm_request_sentinel"
    [ "${#added[@]}"  -gt 0 ] && perm_line+=$'\nPermissions added: '"$(printf '%s, ' "${added[@]}" | sed 's/, $//')"'.'
    [ "${#failed[@]}" -gt 0 ] && perm_line+=$'\nCould not add automatically (add manually to permissions.allow): '"$(printf '%s, ' "${failed[@]}" | sed 's/, $//')"'.'
  fi

  # Compute token delta from handoff generation
  d_in=0; d_out=0
  delta_line=""
  stats_file="/tmp/claude-cliff-stats-${session_id}"
  if [ -f "$stats_file" ]; then
    snap_in=0; snap_out=0; cur_in=0; cur_out=0
    read -r snap_in snap_out < "$stats_file" || true
    read -r cur_in cur_out < <(
      /usr/bin/jq -rs '
        [ .[] | select(.type=="assistant" and (.message.usage // empty)) | .message.usage ]
        | "\(map(.input_tokens  // 0) | add // 0) \(map(.output_tokens // 0) | add // 0)"
      ' "$transcript" 2>/dev/null
    ) || true
    : "${snap_in:=0}" "${snap_out:=0}" "${cur_in:=0}" "${cur_out:=0}"
    d_in=$(( cur_in  - snap_in  ))
    d_out=$(( cur_out - snap_out ))
    d_in_fmt=$(printf  "%'d" "$d_in"  2>/dev/null || echo "$d_in")
    d_out_fmt=$(printf "%'d" "$d_out" 2>/dev/null || echo "$d_out")
    delta_line=$'\nHandoff generation cost: '"${d_in_fmt} in / ${d_out_fmt} out"
    rm -f "$stats_file"
  fi

  msg="${now_hhmm}: 1h cache batch set to expire in 2m (${tokens_fmt} tokens)."
  msg+=$'\n'"Handoff written: ${handoff_path}"
  msg+=$'\nConsider /clear or /quit to avoid paying for cache re-hydration.'
  msg+=$'\nAfterwards, prompt: read '"${handoff_path}"' and continue.'
  msg+="$delta_line"
  msg+="$perm_line"

  /usr/bin/jq -n --arg m "$msg" '{"systemMessage": $m}'
  rm -f "$ready_sentinel"

  # Test mode only: write structured stats file and banner-fired sentinel
  # for the loop harness to detect and analyze.
  if [[ -f "$test_flag" ]]; then
    /usr/bin/jq -n \
      --argjson cliff_epoch    "$cliff_time" \
      --arg     cliff_hhmm     "$cliff_hhmm" \
      --argjson tokens_expiring "$tokens" \
      --argjson cost_in        "$d_in" \
      --argjson cost_out       "$d_out" \
      --argjson banner_fired_at "$now_epoch" \
      '{
        cliff_epoch:      $cliff_epoch,
        cliff_hhmm:       $cliff_hhmm,
        tokens_expiring:  $tokens_expiring,
        handoff_cost_in:  $cost_in,
        handoff_cost_out: $cost_out,
        banner_fired_at:  $banner_fired_at
      }' > "${cwd:-.}/HANDOFF-stats-${session_short}.json"
    touch "/tmp/claude-cliff-banner-fired-${session_id}"
  fi
fi
