#!/usr/bin/env bash
# Stop hook (sync): emits a systemMessage banner ~2 minutes before the
# 1h cache cliff, once HANDOFF.md has been generated by cache-cliff-handoff.sh.
set -uo pipefail

input=$(cat)
transcript=$(printf '%s' "$input" | /usr/bin/jq -r '.transcript_path // empty' 2>/dev/null)
session_id=$(printf '%s' "$input" | /usr/bin/jq -r '.session_id    // "default"' 2>/dev/null)
cwd=$(       printf '%s' "$input" | /usr/bin/jq -r '.cwd           // empty'     2>/dev/null)

[[ -z "$transcript" || ! -f "$transcript" ]] && exit 0

now_epoch=$(date +%s)

oldest_ts=$(
  /usr/bin/jq -rs --argjson now "$now_epoch" '
    [ .[]
      | select(.type=="assistant" and (.message.usage // empty))
      | { ts: (.timestamp | sub("\\.[0-9]+Z$"; "Z") | fromdateiso8601),
          m1h: (.message.usage.cache_creation.ephemeral_1h_input_tokens // 0) }
    ]
    | [ .[] | select(.ts > ($now - 3600) and .m1h > 0) ]
    | sort_by(.ts) | first // {ts: 0}
    | .ts | floor
  ' "$transcript" 2>/dev/null
)

oldest_ts=${oldest_ts:-0}

# Test override: echo a future epoch into this file to skip transcript parsing
# e.g. echo $(( $(date +%s) + 180 )) > /tmp/claude-cliff-test-cliff
test_flag="/tmp/claude-cliff-test-cliff"
if [[ -f "$test_flag" ]]; then
  cliff_time=$(cat "$test_flag")
else
  [ "$oldest_ts" -le 0 ] && exit 0
  cliff_time=$(( oldest_ts + 3600 ))
fi

rem=$(( cliff_time - now_epoch ))

ready_sentinel="/tmp/claude-cliff-handoff-ready-${session_id}"
if [ "$rem" -gt 0 ] && [ "$rem" -le 120 ] && [ -f "$ready_sentinel" ]; then
  handoff_path="${cwd:-.}/HANDOFF.md"
  now_hhmm=$(date '+%H:%M')
  printf '{"systemMessage": "%s: 1h cache batch set to expire in 2m.\nHANDOFF.md document generated in local directory.\nConsider /clear or /quit to avoid paying for cache re-hydration.\nAfterwards, prompt: read %s and continue."}\n' \
    "$now_hhmm" "$handoff_path"
  rm -f "$ready_sentinel"
fi
